# Generated by Django 5.1.4 on 2024-12-15 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('discription', models.TextField(max_length=600)),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(default='default/CHOOSE.png', upload_to='avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('discription', models.TextField(max_length=600)),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(default='default/CHOOSE.png', upload_to='avatars/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_wiki.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField(max_length=600)),
                ('role', models.CharField(max_length=100)),
                ('birth_day', models.CharField(max_length=20)),
                ('image', models.ImageField(default='default/CHOOSE.png', upload_to='avatars/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_wiki.group')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('discription', models.TextField(max_length=600)),
                ('duration', models.DurationField()),
                ('file', models.FileField(upload_to='songs/')),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music_wiki.album')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_wiki.group')),
            ],
        ),
    ]
