# Generated by Django 5.1.4 on 2024-12-22 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_wiki', '0003_alter_album_image_alter_group_image_alter_song_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'альбом', 'verbose_name_plural': 'альбомы'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'группа', 'verbose_name_plural': 'группы'},
        ),
        migrations.AlterModelOptions(
            name='groupmember',
            options={'verbose_name': 'участник группы', 'verbose_name_plural': 'участники группы'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'песня', 'verbose_name_plural': 'песни'},
        ),
        migrations.RemoveField(
            model_name='album',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='group',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='song',
            name='discription',
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='album',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music_wiki.group', verbose_name='группа'),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(default='default/album/album.png', upload_to='avatars/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название альбома'),
        ),
        migrations.AlterField(
            model_name='group',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(default='default/group/group.png', upload_to='avatars/', verbose_name='группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=50, verbose_name='название группы'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='биография'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='birth_day',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='день рождения'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupmembers', to='music_wiki.group', verbose_name='группа'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='image',
            field=models.ImageField(default='default/groupmember/avatar.png', upload_to='avatars/', verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='name',
            field=models.CharField(max_length=50, verbose_name='имя члена группы'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='роль'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='music_wiki.album', verbose_name='альбом'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(verbose_name='длительность'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(default='default/song/audio.mp3', upload_to='songs/', verbose_name='аудиофайл'),
        ),
        migrations.AlterField(
            model_name='song',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music_wiki.group', verbose_name='группа'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, null=True, verbose_name='лирика'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название песни'),
        ),
    ]
